name: ichi
description: ICHI - music learning app
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  cloud_firestore: ^6.2.0
  firebase_auth: ^6.3.0
  firebase_core: ^4.6.0
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logoo.png