// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdJek5l2fxDFL2Njt3-l9S5VJn97hefmQ',
    appId: '1:658364611913:web:5d7aec3fb96f4015bfee98',
    messagingSenderId: '658364611913',
    projectId: 'ichi-admin',
    authDomain: 'ichi-admin.firebaseapp.com',
    storageBucket: 'ichi-admin.firebasestorage.app',
    measurementId: 'G-13F04HYG8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMYZSZrAepTufM6SRYLuiV6yZidUQFLmY',
    appId: '1:658364611913:android:fcb9e905b5d1d5f4bfee98',
    messagingSenderId: '658364611913',
    projectId: 'ichi-admin',
    storageBucket: 'ichi-admin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcpAUVKCZdi4wmmQVLQzxpwedK9RgLhb8',
    appId: '1:658364611913:ios:e17354591efea962bfee98',
    messagingSenderId: '658364611913',
    projectId: 'ichi-admin',
    storageBucket: 'ichi-admin.firebasestorage.app',
    iosBundleId: 'com.example.ichi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcpAUVKCZdi4wmmQVLQzxpwedK9RgLhb8',
    appId: '1:658364611913:ios:e17354591efea962bfee98',
    messagingSenderId: '658364611913',
    projectId: 'ichi-admin',
    storageBucket: 'ichi-admin.firebasestorage.app',
    iosBundleId: 'com.example.ichi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdJek5l2fxDFL2Njt3-l9S5VJn97hefmQ',
    appId: '1:658364611913:web:9aceebfb81068fdebfee98',
    messagingSenderId: '658364611913',
    projectId: 'ichi-admin',
    authDomain: 'ichi-admin.firebaseapp.com',
    storageBucket: 'ichi-admin.firebasestorage.app',
    measurementId: 'G-NB3G2ZC9FT',
  );
}
